### ISSUE TITLE
How to make font size bigger

### ISSUE THREAD

**Issue by rparree** [tmtk75/jumly#24]
Hi,

What would be the easiest way (and maintainable) to increase the font size. I am currently looking if i can use this inside [reveal.js](https://github.com/hakimel/reveal.js/). 

I will need to use it for projected presentations, so a font size of 14 or 18 would be great. What would be the best way forward (i already saw you are not using scss).

I am fiddling around with my own CSS, but that solution feels to brittle (plus i am having problems with spacing etc)

Thanks.,
.

**Comment by tmtk75** [comment]
Fixed at 5643e4f3082aefc90f38c047170bf41d912794c0
